<?xml version="1.0" encoding="utf-8"?>
<project xmlns:mvn="antlib:org.apache.maven.resolver.ant" name="MapRouletteFlow" default="dist" basedir=".">
  <property name="plugin.src.dir" value="src/main/java"/>
  <property name="plugin.test.dir" location="src/test"/>
  <property name="plugin.resources.dir" value="src/main/resources"/>
  <!-- enter the SVN commit message -->
  <property name="commit.message" value="Commit message"/>
  <!-- enter the *lowest* JOSM version this plugin is currently compatible with -->
  <property name="plugin.main.version" value="19528"/>
  <property name="plugin.author" value="Richard Zeng"/>
  <property name="plugin.class" value="io.github.richardqzeng.josm.maprouletteflow.MapRouletteFlowPlugin"/>
  <property name="plugin.description" value="Focused, web-style MapRoulette challenge workflows in JOSM"/>
  <property name="plugin.icon" value="images/maprouletteflow/plugin.svg"/>
  <property name="plugin.link" value="https://github.com/RichardQZeng/MapRouletteFlow"/>
  <property name="plugin.minimum.java.version" value="17"/>
  <property name="java.lang.version" value="17"/>
  <property name="plugin.canloadatruntime" value="false"/>
  <!-- ** include targets that all plugins have in common ** -->
  <import file="../build-common.xml"/>
  <target name="pre-compile" depends="fetch_dependencies">
    <!-- include fetch_dependencies task -->
  </target>
</project>
